baseURL: http://jostorre.me/
languageCode: en-us
title: Jose's Universe
theme: 'PaperMod'
favicon: 'josicon.ico'
googleAnalytics: G-M357ERHZ0B

ShowReadingTime: true
ShowShareButtons: true
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: false
disableSpecial1stPost: false
disableScrollToTop: false
comments: false
hidemeta: false
hideSummary: false
showtoc: false
tocopen: false

params:
  homeInfoParams:
    Title: This is it
    Content: Hello there, this is my personal website.
  

  socialIcons:
    - name: Instagram
      url: 'https://www.instagram.com/jostorre/'
    - name: Linkedin
      url: 'https://www.linkedin.com/in/zetorre/'
    - name: Email
      url: 'mailto:torre.avilais@gmail.com'
    - name: Goodreads
      url: 'https://www.goodreads.com/jostorre'
    - name: Paypal
      url: 'https://www.paypal.me/zetorre'
    - name: Spotify
      url: 'https://open.spotify.com/user/jostorre'
    - name: Twitter
      url: 'https://twitter.com/zeptorre'

menu:
    main:
        - identifier: resources
          name: resources
          url: resources
        - identifier: proj
          name: projects
          url: projects
        - identifier: thoughts
          name: thoughts
          url: /thoughts/
        - identifier: travels
          name: travels
          url: /travels/
        - identifier: me
          name: about me
          url: about
