baseURL: http://jostorre.me/
languageCode: en-us
title: Jose's Universe
theme: 'PaperMod'
favicon: 'josicon.ico'
googleAnalytics: G-M357ERHZ0B

ShowReadingTime: true
ShowShareButtons: true
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: false
disableSpecial1stPost: false
disableScrollToTop: false
comments: false
hidemeta: false
hideSummary: false
showtoc: false
tocopen: false

params:
  homeInfoParams:
    Title: This is it
    Content: Hello there, this is my personal website. My website is an MVP, so it's normal if you find unfinished posts. It is just better to start with something than to wait ages until something is completely ready; Nothing is never completely finished. I  If you really want to know about me, the first thing you’ll probably want to know are my socials...
  

  socialIcons:
    - name: Instagram
      url: 'https://www.instagram.com/jostorre/'
    - name: Linkedin
      url: 'https://www.linkedin.com/in/zetorre/'
    - name: Email
      url: 'mailto:torre.avilais@gmail.com'
    - name: Goodreads
      url: 'https://www.goodreads.com/jostorre'
    - name: Paypal
      url: 'https://www.paypal.me/zetorre'
    - name: Spotify
      url: 'https://open.spotify.com/user/jostorre'
    - name: Twitter
      url: 'https://twitter.com/zeptorre'

menu:
    main:
        - identifier: assets
          name: assets
          url: /assets/
        - identifier: projects
          name: projects
          url: projects
        - identifier: thoughts
          name: thoughts
          url: /thoughts/
        - identifier: travels
          name: travels
          url: /travels/
        - identifier: me
          name: about me
          url: about
